
spring.application.name=careernova-user
server.port=8081


spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/careernova_user
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=your_pg_password
spring.datasource.postgres.driver-class-name=org.postgresql.Driver
spring.datasource.postgres.hikari.maximum-pool-size=10
spring.datasource.postgres.hikari.minimum-idle=5
spring.datasource.postgres.hikari.idle-timeout=30000


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# -----------------------
# JWT Config (optional, if you verify token from Auth)
# -----------------------
jwt.secret=YOUR_SECRET_KEY_HERE
jwt.expiration=3600